[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Railway will auto-inject PORT
PORT = 8000
PYTHONPATH = "/app"

# Production environment
ENVIRONMENT = "production"
LOG_LEVEL = "info"

# Database and auth (set these in Railway dashboard)
# SUPABASE_URL = ""
# SUPABASE_ANON_KEY = ""
# SUPABASE_JWT_SECRET = ""