# DigitalOcean App Platform Configuration
name: mfa-relay-api
services:
- name: api
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/mfa-relay
    branch: main
    deploy_on_push: true

  # Build settings
  build_command: |
    # Install dependencies
    pip install -r api/requirements.txt

  # Runtime settings
  run_command: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2

  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs

  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

  # Environment variables (set these in DO dashboard)
  envs:
  - key: PORT
    value: "8000"
  - key: PYTHONPATH
    value: "/app"
  - key: ENVIRONMENT
    value: "production"
  - key: LOG_LEVEL
    value: "info"
  # Add these secrets in DigitalOcean dashboard:
  # - SUPABASE_URL
  # - SUPABASE_ANON_KEY
  # - SUPABASE_JWT_SECRET

# Routing
ingress:
  rules:
  - match:
      path:
        prefix: /
    component:
      name: api